### ISSUE TITLE
Unsound integral GEnum instances

### ISSUE THREAD

**Issue by hvr** [dreixel/generic-deriving#29]
```
λ> import Generics.Deriving.Enum
λ> import Data.Int
λ> length $ take 1000 (genum :: [Int8])
1000
```

Same for the other signed/unsigned fixed-size Integral types

**Comment by RyanGlScott** [comment]
I've changed the implementation of `genum` (in bd1c898) for fixed-size integral types so that they no longer produce infinite lists.

Unless you really need it, I'll hold off until the GHC 8.0 release to push a new version of `generic-deriving` to Hackage, since I still need to fix some generics-related code.
