### ISSUE TITLE
Implement Generics.Deriving.Semigroup

### ISSUE THREAD

**Issue by hvr** [dreixel/generic-deriving#33]
I just realised we have `Generics.Deriving.Monoid` but not `Generics.Deriving.Semigroup`. I'm aware there may be some overlap with the `semigroups` package also providing generics-deriving support, but I don't think this should keep `generic-deriving` from providing a facility as well, especially since `Semigroup` has moved into `base`.

**Comment by RyanGlScott** [comment]
I confess that I punted on adding `Generics.Deriving.Semigroup` because it has some tricky design questions. But now that someone's requesting it, we should try to answer them:

1. Currently, `Generics.Deriving.Monoid` provides two different ways of implementing `Monoid` generically. One way is through `memptydefault` (which relies on fields having `Monoid` instances), and another way is through `gmemptydefault` (which uses the separate `GMonoid` type class).

   Clearly we want to add `GSemigroup(gmappend)`, but what about `mappenddefault` that requires the fields to be `Semigroup` instances? If we add that, we wouldn't be able to backport it prior to GHC 8.0 (this library has a no-dependency rule, so `semigroups` is a no-go).

2. Do we make `GSemigroup` a superclass of `GMonoid`? If so, we'd need to make several breaking changes.

**Comment by hvr** [comment]
Btw, according to https://prime.haskell.org/wiki/Libraries/Proposals it'll take several years before `Semigroup` can become a superclass of `Monad` to the point of being almost pointless to make it a superclass at all... but well, nobody cried out yet about this absurdity :-/

However, does the time of when the superclass relationship of `Semigroup`/`Monoid` becomes reality have any effect on the design questions you mention? Or is this independent?

**Comment by RyanGlScott** [comment]
Question 1 has nothing to do with the relationship between `Semigroup` and `Monoid`.

Question 2 has concerns that mirror the SMP, however, since if we do make `GSemigroup` a superclass of `GMonoid`, it will break all `GMonoid` instances in the wild (not that I have a head count of how many actually exist). The alternative would be keeping `GSemigroup` and `GMonoid` separate, at the cost of having two different-but-identical `gmappenddefault` functions in different modules.

**Comment by hvr** [comment]
@RyanGlScott hrm... now that I see it... can't we have a `sappenddefault` when base>=4.9?

**Comment by RyanGlScott** [comment]
We could. And, moreover, we could also have `eqdefault`, `showsPrecdefault`, `fmapdefault`, and other defaults for every other typeclass we imitate in `generic-deriving`.

There's two issues we'd need to address if we decided to do this, however:

* Each `-default` we add seems to require copying all of the same generic machinery, but for a different typeclass. See [these](https://github.com/dreixel/generic-deriving/blob/2b41e22722253268e7e710824ab9fd55ad72d7ac/src/Generics/Deriving/Monoid.hs#L80-L106) two [code](https://github.com/dreixel/generic-deriving/blob/2b41e22722253268e7e710824ab9fd55ad72d7ac/src/Generics/Deriving/Monoid.hs#L110-L136) snippets in `Generics.Deriving.Monoid` for an example.
* Many of our imitation classes do different things than their counterparts in `base`. `GEnum`, for example, works in a completely different way than `Enum` does (which is what allows it to have more instances than `Enum` has). `GShow` produces different output from `Show`. Et cetera. If we start exporting functions that claim to give sensible defaults for `base` typeclasses, should we change our generic equivalents to have the same behavior?

**Comment by RyanGlScott** [comment]
The more I think about this, the more I believe that default implementations of `base` typeclass functions should go in a different package (`base-generics`, perhaps) for the following reasons:

1. We can get around `generic-deriving`'s dependency restrictions. `base-generics` could depend on `semigroups` for default implementations of `Semigroup`/`Monoid`, `transformers-compat` for defaullt implementations of `Eq1`/`Ord1`/`Read1`/`Show1`, and roll its own default implementations for other typeclasses.
2. A generic `fmap` implementation could be derived by making the `GHC.Generics` datatypes themselves instances of `Functor`. This will be possible after [Phab:D1937](https://phabricator.haskell.org/D1937) is merged, but to backport the `Functor` instances, you need to depend on `base-orphans`, which [we don't do](https://github.com/dreixel/generic-deriving/issues/13#issuecomment-113853557) for `generic-deriving`.

**Comment by RyanGlScott** [comment]
JFTR, the "`base-generics`" package that I waxed hypothetical about in https://github.com/dreixel/generic-deriving/issues/33#issuecomment-186954385 now exists as [`generic-data`](http://hackage.haskell.org/package/generic-data).
