### ISSUE TITLE
generic-deriving-1.10.4 syntax error with Haddock from GHC 8.0.x

### ISSUE THREAD

**Issue by peti** [dreixel/generic-deriving#37]
The Haddock phase of generic-deriving-1.10.4 fails with GHC 8.0.x reporting the following error:

~~~~
src/Generics/Deriving/TH.hs:24:1: error:
    parse error on input ‘-- $('deriveAll0'     ''Example) -- Derives Generic instance’
~~~~

**Comment by RyanGlScott** [comment]
Aha! #36 is also about this problem, but I wasn't able to reproduce it before because I didn't realize it was a `haddock` issue in particular.

It's rather odd that this only seems to trip up GHC 8.0 and not earlier versions. Luckily, there is a [simple fix](https://github.com/dreixel/generic-deriving/issues/36#issuecomment-194359932). I'll make a new minor release soon that addresses this issue.
