### ISSUE TITLE
Generics.Deriving.Read 

### ISSUE THREAD

**Issue by yaitskov** [dreixel/generic-deriving#87]
Package provides Generics.Deriving.Show, but there is no counterpart module for Read class.
These classes go hand-in-hand often. Is it delegated to a separate package?

**Comment by RyanGlScott** [comment]
If you're wanting to generically derive `Read` instances, I'd pick the implementation in [`generic-data`](https://hackage.haskell.org/package/generic-data-1.0.0.0/docs/Generic-Data-Internal-Read.html). The `generic-deriving` library does have a proof-of-concept way to derive `Show` instances, but as noted in the [`README.md`](https://github.com/dreixel/generic-deriving/blob/ec2fff74da0d6051d3c88613e324cf94d571c7b9/README.md), it's primarily meant for educational purposes. As a result, I've never seriously entertained the notion of adding `Read` support, since `generic-data` does a much better job of that.
